package com.github.pokemon.pokedex

import com.github.pokemon.pokedex.domain.model.PokemonFullDetail
import com.github.pokemon.pokedex.domain.model.PokemonSprites

val PikachuFullDetail = PokemonFullDetail(
    id = 25,
    name = "Pikachu",
    isFavorite = true,
    imageUrl = "url",
    sprites = PokemonSprites(
        dreamWorld = null,
        home = null,
        officialArtwork = null,
        fallbackFront = null,
    ),
    types = listOf("Electric"),
    abilities = listOf("Lightning Rod"),
    stats = listOf(),
    flavorText = "This is a description",
    weightKg = 1.0,
    heightMeters = 1.0,
    numberLabel = "001",
    genera = "Pikachu",
    color = "Yellow",
    description = "This is a description",
    habitat = "Forest",
    eggGroups = listOf("Monster"),
    captureRate = 1,
    baseHappiness = 1,
    growthRate = "Fast",
    isLegendary = false,
    isMythical = false,
)

val CharmanderFullDetail = PokemonFullDetail(
    id = 25,
    name = "Charmander",
    isFavorite = true,
    imageUrl = "url",
    sprites = PokemonSprites(
        dreamWorld = null,
        home = null,
        officialArtwork = null,
        fallbackFront = null,
    ),
    types = listOf("Water"),
    abilities = listOf("Lightning Rod"),
    stats = listOf(),
    flavorText = "This is a description",
    weightKg = 1.0,
    heightMeters = 1.0,
    numberLabel = "001",
    genera = "Pikachu",
    color = "Yellow",
    description = "This is a description",
    habitat = "Forest",
    eggGroups = listOf("Monster"),
    captureRate = 1,
    baseHappiness = 1,
    growthRate = "Fast",
    isLegendary = false,
    isMythical = false,
)

val SquirtleFullDetail = PokemonFullDetail(
    id = 25,
    name = "Squirtle",
    isFavorite = true,
    imageUrl = "url",
    sprites = PokemonSprites(
        dreamWorld = null,
        home = null,
        officialArtwork = null,
        fallbackFront = null,
    ),
    types = listOf("Water"),
    abilities = listOf("Lightning Rod"),
    stats = listOf(),
    flavorText = "This is a description",
    weightKg = 1.0,
    heightMeters = 1.0,
    numberLabel = "001",
    genera = "Pikachu",
    color = "Yellow",
    description = "This is a description",
    habitat = "Forest",
    eggGroups = listOf("Monster"),
    captureRate = 1,
    baseHappiness = 1,
    growthRate = "Fast",
    isLegendary = false,
    isMythical = false,
)
